### ISSUE TITLE
False positive on comments in template strings

### ISSUE THREAD

**Issue by shawnrice** [ccampbell/sublime-jsx#1]
Hi, just installed but noticed that it will misread template strings with two forward slashes in them.

For instance:
```
const url = isRelative ? `${protocol}://${host}/${path}` : path;
```

will interpret the `//` as a comment and so the rest of the file gets the template string highlighting. Similar problems happen for using `/* */` inside strings. See example:

![screenshot 2017-11-02 11 42 21](https://user-images.githubusercontent.com/3452150/32335298-eaa0e00a-bfc2-11e7-8316-b550ec5aac32.png)

The other jsx package seems to handle these properly:
![screenshot 2017-11-02 11 43 00](https://user-images.githubusercontent.com/3452150/32335349-0a3e1da6-bfc3-11e7-8dbf-0d5898277497.png)

**Comment by sethomas** [comment]
+1

**Comment by ricardo** [comment]
+1

**Comment by darlanmendonca** [comment]
+1
